# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kafkaConsumer_pb2 as kafkaConsumer__pb2


class ConsumeTopicStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Consume = channel.unary_unary(
                '/ConsumeTopic/Consume',
                request_serializer=kafkaConsumer__pb2.Topic.SerializeToString,
                response_deserializer=kafkaConsumer__pb2.TopicMessages.FromString,
                )


class ConsumeTopicServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Consume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsumeTopicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Consume': grpc.unary_unary_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=kafkaConsumer__pb2.Topic.FromString,
                    response_serializer=kafkaConsumer__pb2.TopicMessages.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ConsumeTopic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConsumeTopic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ConsumeTopic/Consume',
            kafkaConsumer__pb2.Topic.SerializeToString,
            kafkaConsumer__pb2.TopicMessages.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
