# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kafkaConsumer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13kafkaConsumer.proto\"\x1b\n\x05Topic\x12\x12\n\ntopic_name\x18\x01 \x01(\t\"\x18\n\x04News\x12\x10\n\x08headline\x18\x01 \x01(\t\"I\n\rTopicMessages\x12\x1a\n\nnews_topic\x18\x01 \x01(\x0b\x32\x06.Topic\x12\x1c\n\rnews_headline\x18\x02 \x03(\x0b\x32\x05.News23\n\x0c\x43onsumeTopic\x12#\n\x07\x43onsume\x12\x06.Topic\x1a\x0e.TopicMessages\"\x00\x62\x06proto3')



_TOPIC = DESCRIPTOR.message_types_by_name['Topic']
_NEWS = DESCRIPTOR.message_types_by_name['News']
_TOPICMESSAGES = DESCRIPTOR.message_types_by_name['TopicMessages']
Topic = _reflection.GeneratedProtocolMessageType('Topic', (_message.Message,), {
  'DESCRIPTOR' : _TOPIC,
  '__module__' : 'kafkaConsumer_pb2'
  # @@protoc_insertion_point(class_scope:Topic)
  })
_sym_db.RegisterMessage(Topic)

News = _reflection.GeneratedProtocolMessageType('News', (_message.Message,), {
  'DESCRIPTOR' : _NEWS,
  '__module__' : 'kafkaConsumer_pb2'
  # @@protoc_insertion_point(class_scope:News)
  })
_sym_db.RegisterMessage(News)

TopicMessages = _reflection.GeneratedProtocolMessageType('TopicMessages', (_message.Message,), {
  'DESCRIPTOR' : _TOPICMESSAGES,
  '__module__' : 'kafkaConsumer_pb2'
  # @@protoc_insertion_point(class_scope:TopicMessages)
  })
_sym_db.RegisterMessage(TopicMessages)

_CONSUMETOPIC = DESCRIPTOR.services_by_name['ConsumeTopic']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOPIC._serialized_start=23
  _TOPIC._serialized_end=50
  _NEWS._serialized_start=52
  _NEWS._serialized_end=76
  _TOPICMESSAGES._serialized_start=78
  _TOPICMESSAGES._serialized_end=151
  _CONSUMETOPIC._serialized_start=153
  _CONSUMETOPIC._serialized_end=204
# @@protoc_insertion_point(module_scope)
